INSERT INTO `desenvolvedoras` (`nome`) VALUES
('Electronic Arts'),
('Ubisoft'),
('Activision'),
('Rockstar Games'),
('Square Enix'),
('Nintendo'),
('CD Projekt Red'),
('Bethesda Softworks'),
('Mediatonic'),
('Capcom'),
('Rocksteady Studio'),
('Telltale Games'),
('Rare'),
('Quantic Dream'),
('Hudson Soft'),
('Bandai Namco'),
('Square'),
('Freebird Games'),
('Tarsier Studios'),
('Saban'),
('Red Barrels'),
('Konami'),
('Tango Gameworks');